# Generated by Django 5.2.4 on 2025-07-06 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbacoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('peso_carne', models.IntegerField(help_text='Cantidad en gramos')),
                ('incluye_papas', models.BooleanField(default=True)),
                ('incluye_ensalada', models.BooleanField(default=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='barbacoa/')),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalletaMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(max_length=100)),
                ('tamaño', models.CharField(default='Estándar', max_length=50)),
                ('ingredientes', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='galletas_mascota/')),
            ],
        ),
        migrations.CreateModel(
            name='Licor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Vino', 'Vino'), ('Whisky', 'Whisky'), ('Tequila', 'Tequila'), ('Ron', 'Ron'), ('Aguardiente', 'Aguardiente'), ('Fernet', 'Fernet'), ('Otro', 'Otro')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('incluye', models.TextField(blank=True)),
                ('disponible', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='licores/')),
            ],
        ),
        migrations.CreateModel(
            name='Mascopaleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tamano', models.CharField(choices=[('Pequeña', 'Pequeña'), ('Mediana', 'Mediana'), ('Grande', 'Grande')], max_length=50)),
                ('sin_lactosa', models.BooleanField(default=True)),
                ('sin_azucar', models.BooleanField(default=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='mascopaletas/')),
            ],
        ),
        migrations.CreateModel(
            name='Picadita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('porciones', models.CharField(blank=True, max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='picaditas/')),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Frutales', 'Frutales'), ('Miche Mix', 'Miche Mix'), ('Yogurt', 'Yogurt'), ('Con Licor', 'Con Licor'), ('Autóctonos', 'Autóctonos'), ('Temporada', 'Temporada'), ('Mascotas', 'Mascotas'), ('Sin Azúcar', 'Sin Azúcar')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_grande', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_pequeno', models.DecimalField(decimal_places=2, max_digits=5)),
                ('especial', models.BooleanField(default=False)),
                ('temporada', models.BooleanField(default=False)),
                ('disponible', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='sabores/')),
            ],
        ),
        migrations.CreateModel(
            name='Sanduche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo_pan', models.CharField(blank=True, max_length=50)),
                ('incluye_papas', models.BooleanField(default=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='sanduches/')),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Paleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chocolate_bañado', models.BooleanField(default=False)),
                ('imagen_personalizada', models.ImageField(blank=True, null=True, upload_to='paletas/')),
                ('sabor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.sabor')),
                ('toppings', models.ManyToManyField(blank=True, to='productos.topping')),
            ],
        ),
    ]
