# Generated by Django 5.2.3 on 2025-07-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascopaleta',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
