# Generated by Django 5.2.3 on 2025-07-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sabor',
            old_name='precio',
            new_name='precio_grande',
        ),
        migrations.AddField(
            model_name='sabor',
            name='precio_pequeno',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
