# Generated by Django 5.2.3 on 2025-07-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_rename_precio_sabor_precio_grande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sabor',
            name='categoria',
            field=models.CharField(choices=[('miche_mix', 'Miche Mix'), ('yogurt', 'Paletas de Yogurt'), ('licor', 'Paletas con Licor'), ('frutales', '🍒 Paletas Frutales')], max_length=100),
        ),
    ]
